fixtures:
  repositories:
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
  symlinks:
    carbon: "#{source_dir}"
